@startuml
'https://plantuml.com/class-diagram
allow_mixing
skinparam TitleFontSize 18
skinparam ClassFontSize 16
skinparam RectangleFontSize 16
skinparam InterfaceFontSize 16

title RocketChat

rectangle NodeJS {
    interface EventEmitter
}

rectangle apps {
    rectangle meteor {
        rectangle client {
            class routes {
                route ('/', '/login', '/meet/:rid', '/directory/:tab?', /omnichannel-directory/:page?/:bar?/:id?/:tab?/:context?', '/livechat-queue', '/terms-of-service', '/privacy-policy', '/legal-notice', '/register/:hash', '/invite/:hash', '/setup-wizard/:step?', '/mailer/unsubscribe/:_id/:createdAt', '/login-token/:token', '/reset-password/:token', '/oauth/authorize', '/oauth/error/:error' )
            }
            rectangle hooks {
            }
        }

        rectangle server {
            class WebApp {

            }
        }
    }
    rectangle api {
        rectangle server {
            rectangle v1 {
                class API{
                }
            }
        }
    }
}

rectangle connect {
    interface Server extends NodeJS.EventEmitter
}


WebApp ..> Server: connectHandlers ('/avatar/room/', '/avatar/', '/data-export/')
WebApp ..> Server: rawConnectHandlers ('/health', '/_timesync`)





@enduml
